# See https://geekdocs.de/usage/configuration/
# for more information on how to configure this file

---
baseURL: https://mbraverm.github.io
title: Mark Braverman's Home Page
theme: hugo-geekdoc
pygmentsUseClasses: true
pygmentsCodeFences: true
timeout: 180000

# Geekdoc configuration
disablePathToLower: true
enableGitInfo: false

# Needed for mermaid shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

params:
#  geekdocMenuBundle: true
  geekdocToC: 3

  geekdocRepo: https://github.com/mbraverm/mbraverm.github.io
  geekdocEditPath: edit/main/content

  geekdocSearch: true
  geekdocSearchShowParent: true

  geekdocLogo: /media/princeton-shield-square.png

